config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users
  root 'posts#index'

  get 'pages/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #active storage rails 5+
  has_one_attached :image
  has_one_attached :banner
  # rich text editor rails 6+
  has_rich_text :body

  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 20}

  # paginagion
  self.per_page = 10

  # firnedly id
  extend FriendlyId
  friendly_id :title, use: :slugged

  #resize image
  def optimize_image (image, x ,y)
    return image.variant(resize_to_fill: [x, y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin!

  private

  def is_admin!
    if current_user && current_user.admin
    else
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:show, :index]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
                      .paginate(page: params[:page], per_page: 8)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.views = @post.views + 1
    @post.save
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-secondary container min-vh-100">
    <div class="bg-white min-vh-100">
      <%= render 'partials/nav' %>
      <div class="container">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Index</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', pages_about_path, class: 'nav-link'  %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li>
                  <%= link_to 'New post', new_post_path , class: 'dropdown-item' %>
                </li>
                <li>
                  <%= link_to "User settings", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to 'Logout', destroy_user_session_path , class: 'dropdown-item', method: :delete  %>
                </li>
              </ul>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path , class: 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path , class: 'nav-link'  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<div class="row">
  <div class="offset-2 col-8">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-2">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-2">
      <%= form.label :body %>
      <%= form.rich_text_area :body %>
    </div>

    <div class="mb-2">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control' %>
    </div>

    <div class="mb-2">
      <%= form.label :banner %>
      <%= form.file_field :banner, class: 'form-control' %>
    </div>

    <div class="d-grid gap-2">
      <%= form.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="my-4 mx-4">

  <div class="row">
    <% @posts.each do |post| %>
      <div class="card col-3 m-1" style="width: 18rem;">
        <%= image_tag post.image, class: 'card-img-top' %>
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <%= link_to 'View Post', post, class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row text-center">
    <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row text-center">
  <div class="col-12">
    <div class="d-grid gap-2">
      <%= image_tag @post.banner, class: 'banner' %>
    </div>
  </div>

  <div class="col-12 my-4">
    <h2><%= @post.title %></h2>
    <small>
    Created at: <%= @post.created_at.strftime("%m/%d/%Y") %>
    <b>By: <%= @post.user.email %> </b>
    |
    <%= @post.views %>
    views
    </small>
  </div>

  <div class="col-12 px-4 body">
    <%= @post.body %>
  </div>
</div>